crawl_orgs:
  - HL7
  - hl7dk
  - HL7NZ
  - hl7-eu
  - who-int
  - aehrc
  - ahdis
  - arkhn
  - Automate-Medical
  - bcgov
  - BIH-CEI
  - Carequality
  - clarotech
  - dvci
  - experimental-kitchen
  - GA4GH-Pedigree-Standard
  - gatekeeper-project
  - hl7-be
  - hl7-it
  - HL7Austria
  - hl7ch
  - hl7germany
  - HL7Sweden
  - I-TECH-UW
  - IHE
  - inferno-community
  - medizininformatik-initiative
  - mmg-fhir-ig
  - ncpi-fhir
  - openhie
  - oridashi
  - paciowg
  - phenopackets
  - phuse-org
  - SaraAlert
  - standardhealth
  - WorldHealthOrganization